# Generated by Django 6.0 on 2026-01-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='otp',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='otp_hash',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
