# Generated by Django 6.0 on 2025-12-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
