# Generated by Django 6.0 on 2026-01-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
