# Generated by Django 6.0 on 2026-01-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_history', '0002_customer_nic'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=20),
        ),
    ]
